max_qps: 100

psql:
  db: yuntan_device
  host: 127.0.0.1
  port: 5432
  user: postgres
  pass: ""
  idleTime: 500
  # ^ Amount of time for which an unused resource is kept alive.
  # The smallest acceptable value is 0.5 seconds.
  #
  # The elapsed time before closing may be a little longer than
  # requested, as the reaper thread wakes at 1-second intervals.
  maxResources: 10
  # ^ Maximum number of resources to maintain per stripe.  The
  # smallest acceptable value is 1.
  #
  # Requests for resources will block if this limit is reached on a
  # single stripe, even if other stripes have idle resources
  # available.

redis:
  db: 0
  host: redis
  port: 6379
  enable: false
  maxConnections: 50
  idleTime: 30

# emqx_auth:
#   superadmin: superadmin
#   password: password
#   admin_list:
#   - key: 1234567890abcdef
#     password: password
#   - key: 1234567890abcggg
#     password: password

# auth_enable: True
# auth_key: fnsNK0ro6wg6RkWcXJx3Ft0

mqtt: mqtt://user:passwd@gw.huabot.com:11883
# allow_keys:
# - 1234567890abcdef
